### ISSUE TITLE
Must be able to update information for inventory entries

### ISSUE THREAD

**Issue by nishanthsanjeev** [CSCI-GA-2820-SP23-003/inventory#2]
**As an** Inventory Manager
**I need** to be able to update the information for a chosen inventory entry  
**So that** I can update this entry's quantity in our warehouse, as well as its restock levels and condition.
   
 ### Details and Assumptions
We will store the account details in a database
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the service is running and a target product exists in the database
When I update an inventory entry
Then the entry should be updated in the database
```

**Comment by shradhaiyer** [comment]
If the quantity reaches 0, do we delete the product?
