### ISSUE TITLE
Add query string support to List function

### ISSUE THREAD

**Issue by nishanthsanjeev** [CSCI-GA-2820-SP23-003/inventory#25]
**As an** Inventory Manager
**I need** to be able to provide query strings to our List function
**So that** the query capability can function
   
 ### Details and Assumptions
- We will store the inventory details in a database
- We will only be able to query on name, condition & restock level
- Base URL should be /inventory
- Changes must only be made to routes.py

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I pass a query string to my List function
 Then the query capability works as expected
```

**Comment by sahildeshpande25** [comment]
Must be done in the list all inventory items function. Similar to [this](https://github.com/nyu-devops/lab-flask-tdd/blob/8fb4b374162bb46f7e91a220db4373aaa12605b8/service/routes.py#L69)
