### ISSUE TITLE
Create a Kubernetes cluster on IBM Cloud

### ISSUE THREAD

**Issue by sahildeshpande25** [CSCI-GA-2820-SP23-003/inventory#30]
**As a** developer
**I need** a Kubernetes cluster
**So that** I can deploy the Inventory microservice to IBM cloud
   
 ### Details and Assumptions
 * We will use IBM cloud
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have an IBM cloud account
 When I create and set up a Kubernetes cluster
 Then I should be able to deploy the Inventory microservice 
```

**Comment by rachitjain2706** [comment]
How about adding the IBM Cloud CLI to this story?
