### ISSUE TITLE
Create and Setup prod Kubernetes namespace

### ISSUE THREAD

**Issue by sahildeshpande25** [CSCI-GA-2820-SP23-003/inventory#33]
**As a** developer
**I need** a Kubernetes namespace for the production version of the Inventory service
**So that** I can deploy the production version of the Inventory service
   
 ### Details and Assumptions
 * This is a Kubernetes namespace, not a Container Registry namespace
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the Kubernetes cluster is running
 When I create and setup a prod Kubernetes namespace
 Then I should be able to deploy the Inventory service to the prod Kubernetes namespace
```

**Comment by rachitjain2706** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15117784/230641555-3d6520a9-354f-4963-802b-762eba206f66.png">

Created prod namespace
