### ISSUE TITLE
Create a webpage to administer the application through a UI

### ISSUE THREAD

**Issue by sahildeshpande25** [CSCI-GA-2820-SP23-003/inventory#34]
**As an** Inventory Manager
**I need** a user interface for the Inventory application
**So that** I can perform CRUD and list operations through the UI
   
 ### Details and Assumptions
 * Webpage should be available at `/` or `/home`
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I enter the URL for the application
 Then I should see a UI with supported operations for CRUD and list
```

**Comment by rachitjain2706** [comment]
Would be better to make it into smaller stories for each of the CRUD operations.

**Comment by sahildeshpande25** [comment]
Yes, I'll split it into smaller stories before the next backlog refinement
