### ISSUE TITLE
Add RESTOCK Action as a URL

### ISSUE THREAD

**Issue by zhengtr** [CSCI-GA-2820-SP23-003/inventory#37]
**As a** Inventory Manager
**I need** a `restock` Action as URL
**So that** I can perform the `restock` to an Inventory entry
   
 ### Details and Assumptions
 * We will store the inventory details in a database
 * Base URL is /inventory
 * There is a `restock_level` field for each Inventory entry to indicate the restock level 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When call the "PUT http://.../Inventory/<inventory_id>/restock" with an HTTP PUT method
 Then the quantity of the Inventory entry with id=inventory_id should be updated to `restock_level+1`
 The action is succeed if the quantity of the Inventory entry is below `restock_level`, and `HTTP 200 OK` is returned
 Return `HTTP 409_CONFLICT` if the action is not succeed
 Return `HTTP 404_NOT_FOUND` if Inventory entry with id=inventory_id is not found
```

**Comment by sahildeshpande25** [comment]
@zhengtr make sure to uncomment the 409 conflict in error_handlers.py and test it as well when the quantity is above the restock_level
