### ISSUE TITLE
Need to create the database model for inventory entries

### ISSUE THREAD

**Issue by zhengtr** [CSCI-GA-2820-SP23-003/inventory#5]
**As a** Inventory Manager
**I need** to store and manage the data of the inventory entries
**So that** I can keep track of how many of each product we have in our warehouse
   
 ### Details and Assumptions
 * We will store the account details in a database
Schema:

``` gherkin
inventory_id -> int (Primary Key)
inventory_name -> String
inventory_condition -> Enum
inventory_quantity -> int
inventory_restock_level -> int
update_time -> Date
created_at -> Date
```

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 There is a database that stores the information of the products that we have in our ware house
 When I need to manipulate (read, write, delete, etc.) the data of inventory entires
 Then the manipulation can be performed correctly
```

**Comment by nishanthsanjeev** [comment]
May need to assign this to two people.

**Comment by nishanthsanjeev** [comment]
All of us need to discuss schema for this, before implementation. But only one person actually works on the code.

**Comment by shradhaiyer** [comment]
1. inventory_id -> int (Primary Key)
2. inventory_name -> String
3. inventory_condition ->  Enum
4. inventory_quantity -> int
5. inventory_restock_level -> int
6. update_time -> Date

**Comment by rachitjain2706** [comment]
I am a bit confused about `inventory_restock_level` level. When it drops below some threshold, we want to restock that inventory item?

**Comment by sahildeshpande25** [comment]
I think we should rename inventory_name to product_name and include a CREATED AT field as well.

As @rachitjain2706  mentioned, I'm also unsure about how ```inventory_restock_level ``` is supposed to be implemented.

**Comment by rachitjain2706** [comment]
How about changing the `inventory_id` to `product_id`?

I agree regarding `created_at`.

**Comment by nishanthsanjeev** [comment]
Need to clarify requirements for ```inventory_restock_level```.

**Comment by nishanthsanjeev** [comment]
product_id -> int (Primary Key)
product_name -> String
product_condition -> Enum
product_quantity -> int
product_restock_level -> int
update_time -> Date
created_at -> Date

**Comment by zhengtr** [comment]
@sahildeshpande25 I got this error:
`TypeError: Object of type Condition is not JSON serializable` 
when I ran
`response = self.client.post(BASE_URL, json=test_inventory.serialize())
`
where `test_inventory` is an object of `Inventory` class in service/models.py.

I found some posts related to serializing an enum class in [this post](https://stackoverflow.com/questions/24481852/serialising-an-enum-member-to-json). But I am not sure if that's the problem. Would you take a look at it? Thank you!
