### ISSUE TITLE
Deploy the Inventory service to the `dev` namespace in Kubernetes cluster

### ISSUE THREAD

**Issue by zhengtr** [CSCI-GA-2820-SP23-003/inventory#67]
**As a** Developer
**I need** to deploy the Inventory service to the `dev` namespace in Kubernetes cluster
**So that** the service can be ran on the IBM cloud
   
 ### Details and Assumptions
 * This is not the deployment using a CD pipeline
 * Use the Kubernetes CLI command `kubectl -n dev create -f deploy/` to deploy
 * You can also switch to `dev` namespace with `kubectl config set-context --current --namespace dev`, then everything you do after that will be in the `dev` namespace.

 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I go to the URL of the service with proper external IP address and port number of the `dev` namespace
 Then I can see my service running and working on that URL
```

**Comment by sahildeshpande25** [comment]
@zhengtr could you specify dev or prod namespace

**Comment by zhengtr** [comment]
> 

Sure, I will change this to dev and make a new issue for prod.
