### ISSUE TITLE
Add Swagger data models to document the API payloads

### ISSUE THREAD

**Issue by zhengtr** [CSCI-GA-2820-SP23-003/inventory#76]
**As a** developer
**I need** to list the models of the Inventory service
**So that** users know how to send payloads
   
 ### Details and Assumptions
 * Models should be available at /apidocs/
 * 2 models - Inventory and Inventory Model
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I visit the /apidocs/ endpoint of the sevice
 Then I should see the different models to see how to send API payloads
```

**Comment by sahildeshpande25** [comment]
Wouldn't this be part of #74 and #75?
