### ISSUE TITLE
Return useful info about inventory at URL /

### ISSUE THREAD

**Issue by sahildeshpande25** [CSCI-GA-2820-SP23-003/inventory#9]
**As an** Inventory Manager
**I need** to see basic info about the inventory and links to List/CRUD operations on the home/index page
**So that** I can get useful info about the inventory and its functions
   
 ### Details and Assumptions
* We will be using Python with Flask
* It should run on port 8000 by default
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I access the index or home URL /
 Then I should be able to see info about the inventory and access its functions
```

**Comment by nishanthsanjeev** [comment]
This information pertains to multiple items throughout the entire warehouse, not just info for a single item.

**Comment by nishanthsanjeev** [comment]
Something very basic; Similar to an API doc.
